version: '3'
services:
  oracle:
    image: gvenzl/oracle-free:latest
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle123
      - APP_USER=test_user
      - APP_USER_PASSWORD=test123
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_PDB=FREEPDB1
    volumes:
      - ./init-scripts:/container-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
